services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "${NGINX_HOST_PORT:?}:80"
    volumes:
      - ./nginx_templates:/etc/nginx/templates
      - ${NGINX_SECRET_DIR:?}:/secrets
      - ${NGINX_PUBLIC_DIR:?}:/public
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.nginx
    logging:
      driver: fluentd
      options:
        tag: docker.minecraft_bedrock_server_roka_viz_aoirint_com.nginx.{{.ID}}
        fluentd-async: "true"

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    restart: always
    depends_on:
      - nginx
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARED_TUNNEL_TOKEN:?}
    logging:
      driver: fluentd
      options:
        tag: docker.minecraft_bedrock_server_roka_viz_aoirint_com.cloudflared.{{.ID}}
        fluentd-async: "true"
